version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r GitHubApi567-hw03a/requirements.txt
      - run:
          name: Run unit tests
          command: |
            python -m unittest discover GitHubApi567-hw03a -v
